os: linux
dist: focal
arch: ppc64le
language: java

services:
    - docker

before_install:
    - sudo apt install -y jq; jq --version

env:
  global:
    - PACKAGE_NAME="dex"
    - VERSION="v2.35.3"
    - LANGUAGE="Nodejs"

jobs:
  include:
    - stage: Build
      name: Build script run
      #before_install: docker pull registry.access.redhat.com/ubi8/ubi:8.7
      before_install:
        # Currently pointing to test branch code of build-script repo
        - git clone https://github.com/nikhil-kalbande/build-scripts.git
        - cd build-scripts; git checkout jen-travis-mig      
      script: 
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - if [ ${VALIDATE_BUILD_SCRIPT} == true ]; then chmod +x ./../build_package.sh; bash -x ./../build_package.sh; fi    
      workspaces:
        create:
          name: build_cache
          paths:
            - .

    - stage: Build docker image
      name: Docker build
      workspaces:
        use: build_cache
      script: 
        - ls -ltr
        - cd build-scripts
        - ls -ltr
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi

    - stage: Run Scanner
      name: Run trivy scan
      workspaces:
        use: build_cache
      script:
        - cd build-scripts
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi      
        - echo "This is trivy scan"
        - ls -ltr
        - cd; cd build-scripts
        - chmod +x ./../trivy_scan.sh; bash -x ./../trivy_scan.sh, fi
        
    - name: Run syft scan
      script:
        - echo "This is syft scan"
    - name: Run clair scan
      script: 
        - echo "This is clair scan"
