os: linux
dist: focal
arch: ppc64le
language: java

services:
    - docker

before_install:
    - sudo apt install -y jq; jq --version

env:
  global:
    - PACKAGE_NAME="dex"
    - VERSION="v2.35.3"
    - LANGUAGE="Nodejs"

jobs:
  include:
    - stage: Build
      name: Build script run
      #before_install: docker pull registry.access.redhat.com/ubi8/ubi:8.7
      before_install:
        # Currently pointing to test branch code of build-script repo
        - git clone https://github.com/nikhil-kalbande/build-scripts.git
        - cd build-scripts; git checkout jen-travis-mig      
      script: 
        - pwd
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - if [ ${VALIDATE_BUILD_SCRIPT} == true ]; then chmod +x ./../build_package.sh; bash -x ./../build_package.sh; fi
      workspaces:
        create:
          name: build_cache
          paths:
            - .

    - stage: Build docker image
      name: Docker build
      workspaces:
        use: build_cache
      script: 
        - ls -ltr
        - cd build-scripts
        - ls -ltr
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        - if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi
        - echo "printing docker images"
        - docker images
        - docker save -o /home/travis/build/saiNammi/currency-travis-poc/image.tar icr.io/ppc64le-oss/dex-ppc64le:v2.35.3
        - ls -ltr
        - cd ~
        - ls -ltr
        - pwd
      workspaces:
        create:
          name: docker_image_tar
          paths:
            - /home/travis/build/saiNammi/currency-travis-poc/image.tar
        

    - stage: Run Scanner
      name: Run trivy scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - docker load -i /home/travis/build/saiNammi/currency-travis-poc/image.tar
        - cd build-scripts
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        #- if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi      
        - chmod +x ../trivy_scan.sh;bash ./../trivy_scan.sh
        
    - name: Run syft scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - docker load -i /home/travis/build/saiNammi/currency-travis-poc/image.tar
        - cd build-scripts
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        #- if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi
        - chmod +x ../syft_scan.sh;bash ./../syft_scan.sh

    - name: Run grype scan
      workspaces:
        use: 
          - build_cache
          - docker_image_tar
      script:
        - docker load -i /home/travis/build/saiNammi/currency-travis-poc/image.tar
        - cd build-scripts
        - chmod +x ../read_buildinfo.sh;bash ./../read_buildinfo.sh
        - source variable.sh
        - echo "BUILD_DOCKER - $BUILD_DOCKER"
        #- if [ ${BUILD_DOCKER} == true ]; then chmod +x ./../build_docker.sh; bash -x ./../build_docker.sh; fi
        - chmod +x ../grype_scan.sh;bash ./../grype_scan.sh
 
